# Generated by Django 5.2.17 on 2026-09-08 07:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('achievement', 'Achievement'), ('certification', 'Certification'), ('course', 'Course'), ('workshop', 'Workshop')], default='certification', max_length=20)),
                ('issued_year', models.PositiveSmallIntegerField()),
                ('image_path', models.CharField(max_length=255)),
                ('credential_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_featured', '-issued_year', 'title'],
            },
        ),
    ]
